export const tableTitlesData = [
    'Year',
    'Name',
    'Made At',
    'The Tech',
    'Link'
]

export const listFiltersData = [
    'All',
    'Front End',
    'Back End',
    'Gatsby', 
    'React', 
    'Node Js',
    'HTML5',
    'SCSS',
    'JavaScript',
    'WordPress', 
    // 'Kentico',
    'PHP',
    'UI/UX Design'
]

export const projectsData = [
    {
        year: `2021`,
        name: `Writing Revolt (v2)`,
        madeAt: `Freelance`,
        featuredTech: `Gatsby, React, Node Js, SASS, WordPress, PHP`,
        filterTags: {
        'All': 'All',         
        'Front End': 'Front End',
            'Back End': 'Back End',
            'Gatsby': 'Gatsby',
            'React': 'React', 
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: ``,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: true,
    },
    {
        year: `2021`,
        name: `Classic Car Cowboy`,
        madeAt: `Freelance`,
        featuredTech: `Next, React, Node Js, SCSS, WordPress, PHP`,
        filterTags: {
        'All': 'All',         
        'Front End': 'Front End',
            'Back End': 'Back End',
            'React': 'React', 
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: ``,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: true,
    },
    {
        year: `2020`,
        name: `DI Repairs`,
        madeAt: `Freelance`,
        featuredTech: `Gatsby, React, Node Js, SASS, WordPress, PHP`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'Gatsby': 'Gatsby',
            'React': 'React',  
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: `https://www.direpairs.com`,
        projectDetailPath: `/projects/di-repairs`,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2020`,
        name: `Trinity Consultants`,
        madeAt: `Imaginuity`,
        featuredTech: `React, Redux, SCSS, SiteFinity, Stripe, Ucommerce`,
        filterTags: {
    'All': 'All',         
    'Front End': 'Front End',
            'React': 'React', 
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
        },
        projectLink: `https://www.trinityconsultants.com`,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `Halcyon`,
        madeAt: `Imaginuity`,
        featuredTech: `React, React Static, Node JS, SCSS, WordPress, PHP`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'React': 'React',  
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
        },
        projectLink: `https://www.visithalcyon.com`,
        projectDetailPath: `/projects/halcyon`,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `We Buy Ugly House's`,
        madeAt: `Imaginuity`,
        featuredTech: `JavaScript, SCSS, HTML5, WordPress, PHP`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
        },
        projectLink: `https://www.webuyuglyhouses.com`,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `Stallion`,
        madeAt: `Imaginuity`,
        featuredTech: `JavaScript, jQuery, PHP, SCSS, Webpack`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
        },
        projectLink: `https://www.stallionoilfield.com/`,
        projectDetailPath: `/projects/stallion`,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `HomeVestors`,
        madeAt: `Imaginuity`,
        featuredTech: `JavaScript, SCSS, HTML5, WordPress, PHP`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
        },
        projectLink: `https://www.homevestors.com`,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `Advancial`,
        madeAt: `Imaginuity`,
        featuredTech: `Javascript, jQuery, CSS, Kentico`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'Kentico': 'Kentico',
        },
        projectLink: `https://www.advancial.org`,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `City of Denton`,
        madeAt: `Imaginuity`,
        featuredTech: `Javascript, jQuery, CSS, Kentico`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'Kentico': 'Kentico',
        },
        projectLink: `https://www.cityofdenton.com/en-us/`,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `University Park`,
        madeAt: `Imaginuity`,
        featuredTech: `Javascript, jQuery, CSS, Kentico`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'Kentico': 'Kentico',
        },
        projectLink: `https://www.uptexas.org`,
        projectDetailPath: `/projects/university-park`,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2019`,
        name: `Personal Portfolio (v2)`,
        madeAt: `Personal`,
        featuredTech: `Svelte, Sapper, SCSS, Netlify`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'Node Js': 'Node Js', 
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: ``,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2018`,
        name: `Creative Revolt`,
        madeAt: `Freelance`,
        featuredTech: `JavaScript, WordPress, PHP, DiviBuilder`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'WordPress': 'WordPress', 
            'PHP': 'PHP',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: `https://www.writingrevolt.com`,
        projectDetailPath: `/projects/creative-revolt`,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2017`,
        name: `Personal Portfolio (v1) `,
        madeAt: `Personal`,
        featuredTech: `JavaScript, GSAP, CSS, HTML`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: ``,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
    {
        year: `2017`,
        name: `Mama's Messy Kitchen`,
        madeAt: `Freelance`,
        featuredTech: `JavaScript, CSS, BootStrap, HTML, PHP`,
        filterTags: {
            'All': 'All',         
            'Front End': 'Front End',
            'Back End': 'Back End',
            'HTML5': 'HTML5',
            'SCSS': 'SCSS', 
            'JavaScript': 'JavaScript',
            'PHP': 'PHP',
            'UI/UX Design': 'UI/UX Design'
        },
        projectLink: ``,
        projectDetailPath: ``,
        githubLink: ``,
        inProgress: false,
    },
]
