
export const skillsData = [
    'React | Redux',
    'Gatsby Js | React Static',
    'Svelte 3 | Sapper',
    'Node Js | Express',
    'JavaScript (ES8+)',
    'jQuery',
    'Asnychronus JavaScript',
    'WebPack',
    'Git (Version Control)',
    'Command Line',
    'SASS | SCSS',
    'CSS',
    'Foundation | Bootstrap',
    'HTML (WCAG compliant)',
    'HTML Emails',
    'GitHub | BitBucket',
    'WordPress | Kentico',
    'Adobe Suite',
    'Figma',
    'SEO',
    'Usability Testing',
    'Agile | Waterfall',
]